fix: run apt command as root (github runners)
Apparently, installing packages insides Ubuntu of a runner enviromnet,
requires root permissions and it makes sense.

Weird that act didn't complained about it, while I was doing tests with
my regular user.

Error on Github Actions was like the followiing when running apt-get
install...:

E: List directory /var/lib/apt/lists/partial is missing. - Acquire (13: Permission denied)
Error: Process completed with exit code 100.